{
	"landlock/ptrace: always accept",
	.prog_type = BPF_PROG_TYPE_LANDLOCK_HOOK,
	.expected_attach_type = BPF_LANDLOCK_PTRACE,
	.insns = {
		BPF_MOV32_IMM(BPF_REG_0, 0),
		BPF_EXIT_INSN(),
	},
	.result = ACCEPT,
},
{
	"landlock/ptrace: forbid arbitrary return value",
	.prog_type = BPF_PROG_TYPE_LANDLOCK_HOOK,
	.expected_attach_type = BPF_LANDLOCK_PTRACE,
	.insns = {
		BPF_MOV32_IMM(BPF_REG_0, 2),
		BPF_EXIT_INSN(),
	},
	.result = REJECT,
	.errstr = "At program exit the register R0 has value (0x2; 0x0) should have been in (0x0; 0x1)",
},
{
	"landlock/ptrace: read context and call dedicated helper",
	.prog_type = BPF_PROG_TYPE_LANDLOCK_HOOK,
	.expected_attach_type = BPF_LANDLOCK_PTRACE,
	.insns = {
		BPF_MOV64_REG(BPF_REG_6, BPF_REG_1),
		BPF_LDX_MEM(BPF_DW, BPF_REG_1, BPF_REG_6,
			offsetof(struct landlock_context_ptrace, tracer)),
		BPF_LDX_MEM(BPF_DW, BPF_REG_2, BPF_REG_6,
			offsetof(struct landlock_context_ptrace, tracer)),
		BPF_RAW_INSN(BPF_JMP | BPF_CALL, 0, 0, 0,
				BPF_FUNC_task_landlock_ptrace_ancestor),
		BPF_MOV32_IMM(BPF_REG_0, 0),
		BPF_EXIT_INSN(),
	},
	.result = ACCEPT,
},
{
	"landlock/ptrace: forbid pointer arithmetic",
	.prog_type = BPF_PROG_TYPE_LANDLOCK_HOOK,
	.expected_attach_type = BPF_LANDLOCK_PTRACE,
	.insns = {
		BPF_MOV64_REG(BPF_REG_6, BPF_REG_1),
		BPF_LDX_MEM(BPF_DW, BPF_REG_1, BPF_REG_6,
			offsetof(struct landlock_context_ptrace, tracer)),
		BPF_ALU64_IMM(BPF_ADD, BPF_REG_1, 1),
		BPF_LDX_MEM(BPF_DW, BPF_REG_2, BPF_REG_6,
			offsetof(struct landlock_context_ptrace, tracee)),
		BPF_ALU64_IMM(BPF_ADD, BPF_REG_2, 1),
		BPF_MOV32_IMM(BPF_REG_0, 0),
		BPF_EXIT_INSN(),
	},
	.result = REJECT,
	.errstr = "R1 pointer arithmetic on task prohibited",
},
